from enum import Enum


class VOL_DIRECTION(Enum):
    UP = 0
    DOWN = 1


class VOLUME_DEVICE(Enum):
    DAC = 0
    MUSES = 1


class VOLUME_ALGORITHM(Enum):
    LINEAR = 0
    LOGARITHMIC = 1


CURRENT_DEVICE_ID = "CURRENT_VOLUME_DEVICE"
CURRENT_MUSES_VOLUME_ID = "CURRENT_MUSES_VOLUME"
CURRENT_VOLUME_ID = "CURRENT_VOLUME"
VOLUME_ALGORITHM_ID = "VOLUME_ALGORITHM"
